---
title: "Introduction to Git for Data Science "
author: "Jeff Li"
date: "`r Sys.Date()`"
output: 
  html_document: 
    toc: true
    toc_depth: 3
    toc_float: true
---

"I maintained my edge by always being a student; you will always have something new to learn". - Jackie Joyner Kersee

**Course Description** 

"Version control is one of the power tools of programming. It allows you to keep track of what you did when, undo any changes you have decided you don't want, and collaborate at scale with other people. This course will introduce you to Git, a modern version control tool that is very popular with data scientists and software developers alike, and show you how it can help you get more done in less time and with less pain."


Ref: Wilson, Greg. https://www.datacamp.com/courses/introduction-to-git-for-data-science.  2018.


Note: some course materials have been adapted for internal training. 


# 1. Basic workflow

*A version control system*: a tool that manages changes made to the files and directories in a project.

* keep track of changes to files

* Notice confilicts between changes made by different people

* Synchronize files between different computers

Git stores all of its extra information in a directory call **.git** located in the root directory of the repository. Never edit or delete anything in *.git*. 


## 1.1  Check the state of a repository 

* *git status*  --- Displays a list of the files that have been modified since the last time changes were saved. 

Git has a staging area in which it stores files with changes that we want to save that haven't been saved yet. 
Working directory --> Staging Area --> .git Directory 


* *git diff*: show all the changes in our repository

* *git diff directory*: show the changes to the files in the directory. 

* *git diff filename*: show the changes to the file. 



## 1.2 Two steps: commit changes to a Git repository

* 1. Add one or more files to the staging area using *add folder/filename.extension*. For example: git add Git/Git.Rmd

* 2. Commit everything in the staging area

How can I tell what's going to be committed?

To compare the state of your files with those in the staging area, you can use git diff -r HEAD. The -r flag means "compare to a particular revision", and HEAD is a shortcut meaning "the most recent commit".

You can restrict the results to a single file or directory using git diff -r HEAD path/to/file, where the path to the file is relative to where you are (for example, the path from the root directory of the repository).

**Interlude: how can I edit a file?**


Unix has a bewildering variety of text editors. In this course, we will sometimes use a very simple one called Nano. If you type nano filename, it will open filename for editing (or create it if it doesn't already exist). You can then move around with the arrow keys, delete characters with the backspace key, and so on. You can also do a few other operations with control-key combinations:

Ctrl-K: delete a line.
Ctrl-U: un-delete a line.
Ctrl-O: save the file ('O' stands for 'output').
Ctrl-X: exit the editor.



Run nano names.txt to edit a new file in your home directory and enter the following four lines:

Lovelace
Hopper
Johnson
Wilson
To save what you have written, type Ctrl-O to write the file out, then Enter to confirm the filename, then Ctrl-X and Enter to exit the editor.



**How do I commit changes?**

To save the changes in the staging area, you use the command *git commit*. It always saves everything that is in the staging area as one unit: as you will see later, when you want to undo changes to a project, you undo all of a commit or none of it.

When you commit changes, Git requires you to enter a log message. This serves the same purpose as a comment in a program: it tells the next person to examine the repository why you made a change.

By default, Git launches a text editor to let you write this message. To keep things simple, you can use -m "some message in quotes" on the command line to enter a single-line message like this:

*git commit -m "Program appears to have become self-aware."*


If you accidentally mistype a commit message, you can change it using the --amend flag.

*git commit --amend - m "new message"* 




## 1.3  *How can I view a repository's history?*

The command git log is used to view the log of the project's history. Log entries are shown most recent first, and look like this:

commit 0430705487381195993bac9c21512ccfb511056d
Author: Rep Loop <repl@datacamp.com>
Date:   Wed Sep 20 13:42:26 2017 +0000

    Added year to report title.
The commit line displays a unique ID for the commit called a hash; we will explore these further in the next chapter. The other lines tell you who made the change, when, and what log message they wrote for the change.

When you run git log, Git automatically uses a pager to show one screen of output at a time. Press the space bar to go down a page or the 'q' key to quit.


## 1.4  **How can I view a specific file's history?**

A project's entire log can be overwhelming, so it's often useful to inspect only the changes to particular files or directories. You can do this using git log path, where path is the path to a specific file or directory. The log for a file shows changes made to that file; the log for a directory shows when files were added or deleted in that directory, rather than when the contents of the directory's files were changed.


## 1.5  **How do I write a better log message?** 

Writing a one-line log message with git commit -m "message"is good enough for very small changes, but your collaborators (including your future self) will appreciate more information. If you run git commit without -m "message", Git launches a text editor with a template.

The lines starting with # are comments, and won't be saved. (They are there to remind you what you are supposed to do and what files you have changed.) Your message should go at the top, and may be as long and as detailed as you want.


Chapter one coveres the basic workflow: 

* git diff

* git status

* git add

* git commit 



# 2. Repositories 

Learn how Git stores information and how we can explore a repository's history

## 2.1 How does Git store information? 
Git uses a three-level structure to store information: 

* Commit: contains metadata: author, commit message, the time the commit happened. 

* Tree - Tracks the names and locations in the repository when a commit happened. 

* Blob (binary large object) - contains a compressed snapshot of the contents of the files when the commit happened. 

## 2.2 What is a hash? 

 Every commit ot a repository has a unique identifier called a hash. Hash: a 40 character hexadecimal string, which is generated by a hash function.
 
 Excise: 
 
 Use cd to go into the xx directory and then run git log. What are the first four characters of the hash of the most recent commit?
 
 
 ## 2.2 How to view a specific commit? 
 * git show + first few characters of the commit's hash
 
 
